"""
agents/reviewer.py

Reviewer Agent
Responsibilities: check the generated code for quality,
point out bugs/issues, and suggest improvements.
"""

from tools.llm import get_llm

REVIEW_PROMPT = """You are the Reviewer Agent in a multi-agent system.

Task: {task}

Here is the code generated by the Coding Agent:
{code}

Review the code:
1. Point out any bugs or issues.
2. Suggest concrete improvements.
3. Give a short overall verdict (Good / Needs work).

Keep the review short and to the point.
"""


def run_reviewer(task: str, code: str) -> str:
    """Reviews the generated code and gives feedback."""
    llm = get_llm(temperature=0.2)
    prompt = REVIEW_PROMPT.format(task=task, code=code)
    response = llm.invoke(prompt)
    return response.content
